### ISSUE TITLE
Add build for tp-link wdr7500 v3

### ISSUE THREAD

**Issue by partizanosBY** [gwlim/openwrt-sfe-flowoffload-ath79#112]
Hi, gwlim. 
Thank you for the hard work of developing and maintaining firmware for our devices.
Earlier, you already build firmware for TP-Link WDR7500 (Archer C7R) v3.0 at my request.
Could you please add support for this model again?

**Comment by gwlim** [comment]
Port it over to ath79 then building can resume

**Comment by AbsoluteRay** [comment]
Appreciate if you can build for wdr7500 v3 for us non-developers, many thanks!

**Comment by gwlim** [comment]
As mentioned please port it over to the ath79 arch first then I will build it

**Comment by gwlim** [comment]
Added in latest release
