### ISSUE TITLE
Add support to D-Link DIR-842 C3

### ISSUE THREAD

**Issue by WalkySVK** [gwlim/openwrt-sfe-flowoffload-ath79#135]
Hello could you add support for D-Link DIR-842 C3 .
Target:    ath79
CPU:    Qualcomm Atheros QCA9563
Switch:    Qualcomm Atheros QCA8337N
WLAN Hardware:    Qualcomm Atheros QCA9563, Qualcomm Atheros QCA9888
WLAN driver:    ath10k-ct

https://openwrt.org/toh/hwdata/d-link/d-link_dir-842_c3
https://openwrt.org/toh/d-link/d-link_dir-842

Thank you

**Comment by gwlim** [comment]
Added in July Image
