### ISSUE TITLE
usign missing

### ISSUE THREAD

**Issue by cybik** [gwlim/openwrt-sfe-flowoffload-ath79#137]
When running `opkg update` from command line, openwrt complains with `usign: not found`.

You might want to pull in https://openwrt.org/packages/pkgdata/usign when building the bins.

**Comment by cybik** [comment]
The fix is to manually obtain the package from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/ , install it using console, then opkg update. This looks like it works, a bit.

**Comment by Zsolteeca** [comment]
So in Luci can't you install any package?

**Comment by cybik** [comment]
Not until I installed the package manually.

**Comment by Zsolteeca** [comment]
But I would like to install luci-app images and I got the code 255 error code
For example.. "pkg_init_from_file: Failed to extract control file from https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-app-simple-adblock_git-20.174.75173-8ff50bf_all.ipk."

You? Can you install these packages to Luci?

**Comment by cybik** [comment]
After I manually downloaded usign using the url https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/usign_2020-05-23-f1f65026-1_mipsel_24kc.ipk , then scp'd it to my device and installed it, I could run opkg update and download other packages again.

**Comment by Zsolteeca** [comment]
Strange..
I had installed the latest version of this firmware to my Linksys WRT1043ND v2 device and I can install any package without the package named "usign"..
What device do you use?

**Comment by cybik** [comment]
WNDRMACv2. It's one of the newest additions to the mix.

I also have a quirky configuration and needed to add a bunch of packages before uhttpd even showed up XD

**Comment by Zsolteeca** [comment]
Sorry I have just installed some packages from luci-app branch.. So I don't know what kind of components does the base section require...

**Comment by gwlim** [comment]
It is to save space by not installing usign

**Comment by cybik** [comment]
Indeed I have.
