### ISSUE TITLE
[low priority] Better(?) folders naming

### ISSUE THREAD

**Issue by nms42** [gwlim/openwrt-sfe-flowoffload-ath79#138]
Is it possible to use '2020-06' naming instead 'JUN-2020' in this repository?

Thanks

**Comment by yonizaf** [comment]
I'm in favor of this.
Main benefit would be sortability - right now it's already annoying to look for the current release somewhere in the middle of the list, and would become worse with time and more releases.

**Comment by gwlim** [comment]
Fixed in latest release
