### ISSUE TITLE
wdr4900 buid

### ISSUE THREAD

**Issue by cosminsstoica** [gwlim/openwrt-sfe-flowoffload-ath79#148]
Hi,
I'm using the latest build (JUL-2020) for Tp-Link WDR4900v1 on a 1000/500 Mbps fiber internet connection. 
Any ideea why Windows clients have lower Download/Upload speed than Linux clients? 
The minimum configuration for the PC is:  I5-8300/i7-8700, 8/16GB RAM and 256/512 nvme.
Not using SQM QOS, and SFE flow offloading is enabled.

![1Gb](https://user-images.githubusercontent.com/20394610/99077755-e672cb80-25c5-11eb-8198-845de9666e25.PNG)

**Comment by gwlim** [comment]
A few things you can check
1. Congestion Control Inside netsh
https://techcommunity.microsoft.com/t5/networking-blog/core-network-stack-features-in-the-creators-update-for-windows/ba-p/339676
2. Windows Device Driver
I have experience before certain realtek driver doesn't do gigabit data transfer but others do

**Comment by cosminsstoica** [comment]
After days of tuning I found "SG TCP Optimizer", which helped me a lot. Still don't get as much speed as on Linux, but now I can reach 800 Mbps upload / 450 Mbps download on Windows. 
I thought it was time to change the router, but I'll keep it for a while. 

Tnx
