### ISSUE TITLE
outdated version

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload-ath79#149]

**Comment by Cereal-Killa** [comment]
Also looking for an update, I had some wifi instability with the last build here on my 1043v3 and I'm running OpenWrt SFE r13152-5019a06fc1 / LuCI Trunk.

**Comment by Zsolteeca** [comment]
@gwlim ?

**Comment by Zsolteeca** [comment]
@gwlim ?
What's up with version change?
